//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFcodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salesman_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salesman_master()
        {
            this.Sales_order = new HashSet<Sales_order>();
        }
    
        public string Salesmanno { get; set; }
        public string Salesmanname { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public Nullable<decimal> Pincode { get; set; }
        public string State { get; set; }
        public decimal Salamt { get; set; }
        public decimal Tgttoget { get; set; }
        public decimal Ytdsales { get; set; }
        public string Remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_order> Sales_order { get; set; }
    }
}
