//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFcodeFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_order
    {
        public string Orderno { get; set; }
        public string Clientno { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public string Delyaddr { get; set; }
        public string Salesmanno { get; set; }
        public string Delytype { get; set; }
        public string Billedyn { get; set; }
        public Nullable<System.DateTime> Delydate { get; set; }
        public string Orderstatus { get; set; }
    
        public virtual Client_master Client_master { get; set; }
        public virtual Salesman_master Salesman_master { get; set; }
    }
}
